[versions]
morphe-patcher = "1.5.2"
#noinspection GradleDependency
smali = "d92701d947"
gson = "2.14.0"
guava = "33.4.8-jre"

[libraries]
morphe-patcher = { module = "app.morphe:patcher", version.ref = "morphe-patcher" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
